### ISSUE TITLE
Upgrade CopyZips from Python 2.7 to 3.x

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/quickstart-cherwell#8]
Python 2.7 is EOL in January 2020. We need to upgrade the CopyZips function prior to then.

**Comment by JonathanWoods11** [comment]
Do we know if this ever got resolved? I imagine not since I just tried to launch this in my account and it failed on the CopyZips creation

**Comment by andrew-glenn** [comment]
It did, but after May 20th. We now consider this issue closed.
